### ISSUE TITLE
Latest miniconda won't install on WSL2

### ISSUE THREAD

**Issue by justinm631** [tux2603/DeepDream#3]
FATAL:   While performing build: while running engine: exit status 1
make: *** [makefile:11: caffe.sif] Error 255

**Comment by tux2603** [comment]
Is there any more output before that?

**Comment by justinm631** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/73143642/96745598-4fcf3800-1394-11eb-8308-da20a046794a.png)

I'm running on wsl2 btw

**Comment by tux2603** [comment]
It might be a kernel compatibility issue. What kernel version are you running? If it's an older kernel, I would recommend either upgrading to kernel 5.6 or newer or using miniconda 4.6.14 instead of the latest version

**Comment by justinm631** [comment]
kernel is 4.19.128-microsoft-standard, I actually got it to install with miniconda 4.6.14. 

but now running the main.py script gives me "/usr/bin/env: ‘python’: No such file or directory"

**Comment by tux2603** [comment]
You'll need to have python installed in you wsl environment. You can either do that through the package manager or by downloading and installing anaconda

**Comment by justinm631** [comment]
ahhh ok I was able to get that working but now I get this lol (btw I really appreciate all the help you've been giving me)

![Screenshot (2)](https://user-images.githubusercontent.com/73143642/96769150-bb250400-13ac-11eb-8126-0ca700ce3926.png)

I had to install cuda toolkit 11-0 in order to have access to nvidia drivers on WSL2, idk if that could be the cause

**Comment by tux2603** [comment]
What nvidia driver versions do you have, both on the main windows system and WSL?

**Comment by justinm631** [comment]
On windows I have version 460.20, its the only driver that needs to be installed since the DirectX WSL driver is installed automatically

https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by tux2603** [comment]
Interesting. It looks like cuda and general GPU support on WSL2 is still somewhat experimental and doesn't support all libraries. It might not be possible to use the GPU accelerated models on windows yet. I am working on adding CPU-only support though. It will be slower, but it should be a lot easier to get working

**Comment by tux2603** [comment]
It might be possible to get it working by running `wsl.exe --update` and then reinstalling the WSL2 environments, but it looks like it's going to be tricky to get CUDA working at best, and impossible at worst.

If dual boot is an option for you and you are interested in getting more into ML and GPU computing, I would highly recommend taking it. Most ML frameworks are designed primarily for Linux based systems and are ported to windows later, so you tend to get much better feature sets and support

**Comment by justinm631** [comment]
yeah i gave up haha but i’ll try the dual boot. thank you so much for your time and help, you’re awesome man!

**Comment by tux2603** [comment]
Sounds like a plan. I was hoping it would be able to work out of the box with WSL, but I guess I'll have to poke around some more.

**Comment by tux2603** [comment]
CPU generation is now working. Just tack on a `--no-gpu` flag to the main.py command
