### ISSUE TITLE
Ignoring Source Layer Issue

### ISSUE THREAD

**Issue by DeepThread** [tux2603/DeepDream#7]
**Describe the bug**
When I run
./main.py -s /home/ryan/DeepDreamVideo/render -d /home/ryan/DeepDreamVideo/Out

I get the below abridged version of the output... Any thoughts. I am on ubuntu 20.04. Installed everything in your guide seemingly to a tee.

I1217 17:33:30.645584 48159 net.cpp:200] inception_3a/relu_3x3 does not need backward computation.
I1217 17:33:30.645588 48159 net.cpp:200] inception_3a/3x3 does not need backward computation.
I1217 17:33:30.645592 48159 net.cpp:200] inception_3a/relu_3x3_reduce does not need backward computation.
I1217 17:33:30.645597 48159 net.cpp:200] inception_3a/3x3_reduce does not need backward computation.
I1217 17:33:30.645601 48159 net.cpp:200] inception_3a/relu_1x1 does not need backward computation.
I1217 17:33:30.645606 48159 net.cpp:200] inception_3a/1x1 does not need backward computation.
I1217 17:33:30.645613 48159 net.cpp:200] pool2/3x3_s2_pool2/3x3_s2_0_split does not need backward computation.
I1217 17:33:30.645618 48159 net.cpp:200] pool2/3x3_s2 does not need backward computation.
I1217 17:33:30.645622 48159 net.cpp:200] conv2/norm2 does not need backward computation.
I1217 17:33:30.645627 48159 net.cpp:200] conv2/relu_3x3 does not need backward computation.
I1217 17:33:30.645630 48159 net.cpp:200] conv2/3x3 does not need backward computation.
I1217 17:33:30.645635 48159 net.cpp:200] conv2/relu_3x3_reduce does not need backward computation.
I1217 17:33:30.645640 48159 net.cpp:200] conv2/3x3_reduce does not need backward computation.
I1217 17:33:30.645645 48159 net.cpp:200] pool1/norm1 does not need backward computation.
I1217 17:33:30.645649 48159 net.cpp:200] pool1/3x3_s2 does not need backward computation.
I1217 17:33:30.645654 48159 net.cpp:200] conv1/relu_7x7 does not need backward computation.
I1217 17:33:30.645658 48159 net.cpp:200] conv1/7x7_s2 does not need backward computation.
I1217 17:33:30.645665 48159 net.cpp:200] data does not need backward computation.
I1217 17:33:30.645685 48159 net.cpp:242] This network produces output prob
I1217 17:33:30.645758 48159 net.cpp:255] Network initialization done.
I1217 17:33:30.690448 48159 upgrade_proto.cpp:53] Attempting to upgrade input file specified using deprecated V1LayerParameter: /opt/model/model.caffemodel
I1217 17:33:30.721181 48159 upgrade_proto.cpp:61] Successfully upgraded file specified using deprecated V1LayerParameter
I1217 17:33:30.722543 48159 net.cpp:744] Ignoring source layer label_data_1_split
I1217 17:33:30.722993 48159 net.cpp:744] Ignoring source layer loss1/ave_pool
I1217 17:33:30.723001 48159 net.cpp:744] Ignoring source layer loss1/conv
I1217 17:33:30.723004 48159 net.cpp:744] Ignoring source layer loss1/relu_conv
I1217 17:33:30.723007 48159 net.cpp:744] Ignoring source layer loss1/fc
I1217 17:33:30.723011 48159 net.cpp:744] Ignoring source layer loss1/relu_fc
I1217 17:33:30.723012 48159 net.cpp:744] Ignoring source layer loss1/drop_fc
I1217 17:33:30.723016 48159 net.cpp:744] Ignoring source layer loss1/classifier
I1217 17:33:30.723019 48159 net.cpp:744] Ignoring source layer loss1/loss
I1217 17:33:30.723655 48159 net.cpp:744] Ignoring source layer loss2/ave_pool
I1217 17:33:30.723666 48159 net.cpp:744] Ignoring source layer loss2/conv
I1217 17:33:30.723670 48159 net.cpp:744] Ignoring source layer loss2/relu_conv
I1217 17:33:30.723676 48159 net.cpp:744] Ignoring source layer loss2/fc
I1217 17:33:30.723680 48159 net.cpp:744] Ignoring source layer loss2/relu_fc
I1217 17:33:30.723682 48159 net.cpp:744] Ignoring source layer loss2/drop_fc
I1217 17:33:30.723685 48159 net.cpp:744] Ignoring source layer loss2/classifier
I1217 17:33:30.723688 48159 net.cpp:744] Ignoring source layer loss2/loss
I1217 17:33:30.725492 48159 net.cpp:744] Ignoring source layer loss3/loss3

**Expected behavior**

**To Reproduce**

**System Specs (please complete the following information):**
 - Operating System: ubuntu
 - Singularity Version: version: 3.6.4
 - Kernel Version (if applicable): [eg, 5.8.0-2-amd64, 4.15.0-106-generic]
 - GPU: 1080ti
 - GPU driver version: 455
 - Installed ram and swap space: 64gb ram 500gbswap

**Additional context**

**Comment by tux2603** [comment]
Those are just debug logs that are provided by caffe, and they look like the expected output. As far as I can tell, there's some sort of setting in caffe that will ignore any output layers that aren't directly needed. As long as the images are being generated properly, all of that can be safely ignored.

On a side note, since you seem to be generating a video, it might be worth adding in a `--blend` or a `-b` option. Without it, the dreams are computed individually per frame, which can lead to a lot of jumpiness. Adding in the blend option will mix in a bit of the previous frame with each subsequent frame, smoothing things out significantly.
