### ISSUE TITLE
could not open image /root/DeepDream/caffe.sif: image format not recognized

### ISSUE THREAD

**Issue by juejixiaohaipi** [tux2603/DeepDream#9]
could not open image /root/DeepDream/caffe.sif: image format not recognized

**Comment by tux2603** [comment]
Would you be able to fill out the diagnostic information?

**To Reproduce**
Steps to reproduce the behavior:

**System Specs (please complete the following information):**
 - Operating System: [eg, ubuntu, arch]
 - Singularity Version: [eg, 3.6.3]
 - Kernel Version (if applicable): [eg, 5.8.0-2-amd64, 4.15.0-106-generic]
 - GPU: [eg, 1050ti, 2x2080s]
 - GPU driver version: [eg, 440.64]
 - Installed ram and swap space: [eg, 16GB ram, 8GB swap]

**Comment by juejixiaohaipi** [comment]
how much storage space need？
maybe my centos has enough disk space？
does 25G enough？

**Comment by juejixiaohaipi** [comment]
i run make.but stop on the last step:build caffe.sif

**Comment by juejixiaohaipi** [comment]
2gb ram 1gb swap 1 core 35gb disk space but 25gb left before make.

**Comment by tux2603** [comment]
25gb of storage should be enough for the image, but the ram and cpu are probably cutting it pretty tight. I'd recommend at least 8gb of ram for building, and then at least four cpu cores for when you actually run the container. Also, what version of singularity do you have installed, and what linux kernel version are you running on?

**Comment by juejixiaohaipi** [comment]
CentOS Linux release 8.3.2011

**Comment by juejixiaohaipi** [comment]
i have ajust my centos,to 2 cores and 40gb disk space

**Comment by juejixiaohaipi** [comment]
singularity version 3.7.1

**Comment by juejixiaohaipi** [comment]
https://imgchr.com/i/sgGv1U

**Comment by juejixiaohaipi** [comment]
maybe there still has not enough disk space.

**Comment by juejixiaohaipi** [comment]
any thing wrong i was do?

**Comment by juejixiaohaipi** [comment]
https://imgchr.com/i/sgJUBj

**Comment by juejixiaohaipi** [comment]
INFO:    Creating SIF file...
FATAL:   While performing build: while creating squashfs: create command failed: exit status 1: 
Write failed because No space left on device

FATAL ERROR:Failed to write to output filesystem
make: *** [makefile:11：caffe.sif] 错误 255

**Comment by juejixiaohaipi** [comment]
there left space is 25.5G

**Comment by tux2603** [comment]
It might be worth giving it a bit larger disk space. The image should be small enough to fit, but it might help. It might be that it's running out of memory, since the images are largely built there. If it doesn't work after giving me drive space, you could try allocating more swap.

One other thing that you could try is a more up to date operating system. That likely isn't causing the issue, but it won't hurt

**Comment by juejixiaohaipi** [comment]
would you tell me how much disk space necessary,thanks!

**Comment by tux2603** [comment]
I'm not really sure. I would have thought that 25gb free would have been enough, but apparently not. If you have available space on the host you could try 64gb

**Comment by juejixiaohaipi** [comment]
thank you,I'll have a try again

**Comment by juejixiaohaipi** [comment]
bvlc_googlenet/bvlc_googlenet.caffemodel doesn't exist

**Comment by juejixiaohaipi** [comment]
I have install success

**Comment by juejixiaohaipi** [comment]
There is a new bug:
singularity exec --writable-tmpfs --pwd=/opt/src --nv -B bvlc_googlenet/bvlc_googlenet.caffemodel:/opt/model/model.caffemodel -B bvlc_googlenet/deploy.prototxt:/opt/model/deploy.prototxt -B src:/opt/src -B ./../DeepDreamVideo/frames:/opt/images/source -B ./../DeepDreamVideo/frames_out:/opt/images/destination caffe.sif conda run --no-capture-output -n gpu ./dream.py --num-iterations 1 --octave-count 4 --octave-scale 1.3 --steps-per-octave 10 --maximize inception_4c/output --jitter 32 --use-gpu 0
INFO:    Could not find any nv files on this host!
WARNING: skipping mount of /home/jerry/app/DeepDream/bvlc_googlenet/bvlc_googlenet.caffemodel: stat /home/jerry/app/DeepDream/bvlc_googlenet/bvlc_googlenet.caffemodel: no such file or directory
FATAL:   container creation failed: mount /home/jerry/app/DeepDream/bvlc_googlenet/bvlc_googlenet.caffemodel->/opt/model/model.caffemodel error: while mounting /home/jerry/app/DeepDream/bvlc_googlenet/bvlc_googlenet.caffemodel: mount source /home/jerry/app/DeepDream/bvlc_googlenet/bvlc_googlenet.caffemodel doesn't exist

**Comment by juejixiaohaipi** [comment]
can you provide me a detail Instructions for use

**Comment by tux2603** [comment]
Run the command `wget http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel -O /home/jerry/app/DeepDream/bvlc_googlenet/bvlc_googlenet.caffemodel` to get the file

**Comment by juejixiaohaipi** [comment]
thanks, when i run the command:./main.py -s ./../DeepDreamVideo/frames -d ./../DeepDreamVideo/frames_out --no-gpu

in the out,can't find any errors!but the directory frames_out is empty!!

**Comment by juejixiaohaipi** [comment]
https://ae06.alicdn.com/kf/U5e42c391dcb64ab9a4f3db5a93ac66372.png

**Comment by juejixiaohaipi** [comment]
the directory frames_out is empty.

**Comment by tux2603** [comment]
~~How long did you let the command run? It will likely take five minute or more per frame with those specs. Also, what is the full output of the command?~~

**Comment by tux2603** [comment]
Wait, never mind, I found the problem. The input images have to be jpeg's, not png's. Run the command `find . -name "*.png" -exec mogrify -format jpg {} \;` In the frames directory to convert them automatically

**Comment by juejixiaohaipi** [comment]
thank you,i will have a try!

**Comment by juejixiaohaipi** [comment]
i got the frames_out.yet dispose very slow!!

**Comment by juejixiaohaipi** [comment]
after i run this command:./main.py -s ./../DeepDreamVideo/frames_jpg -d ./../DeepDreamVideo/frames_out --no-gpu


anythig else i need do?

**Comment by juejixiaohaipi** [comment]
https://ftp.bmp.ovh/imgs/2021/01/8f81f3b1df495cd8.png

**Comment by juejixiaohaipi** [comment]
https://ftp.bmp.ovh/imgs/2021/01/01886e37f0bd5d96.png

**Comment by tux2603** [comment]
I would recommend adding on the `-b` flag to that command to help smooth out the video, but besides that you should be good to go!

**Comment by juejixiaohaipi** [comment]
finally,i run the program successfully!but this program is very slow,how can i fast it?

**Comment by juejixiaohaipi** [comment]
with a 58seconds video,the program run 7hours!

**Comment by tux2603** [comment]
Yes. It's a very computationally complex program, and you're running it on a very low powered system. One way to make it run faster would be to decrease the resolution of the video, but the best way would be to run it on a more powerful system. Ideally, the system would have a cuda capable GPU, but a CPU only system can also be used with a higher core count.

**Comment by juejixiaohaipi** [comment]
hello,did you know which model do make this effect.
![](https://ftp.bmp.ovh/imgs/2021/01/baefa28d6d1e1159.jpg)

**Comment by juejixiaohaipi** [comment]
i found the model name is trippy!where can i  get it.
i have Traverse the directory: https://github.com/BVLC/caffe/tree/master/models
,but can not found.
